spring:
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
    lettuce:
      pool:
        min-idle: 0   #连接池最小空闲连接数
        max-idle: 8   #连接池最大空闲连接数
        max-active: 8  #连接池最大连接数
        max-wait: -1ms  #连接池最大阻塞等待时间，负值表示没有限制


  application:
    name: Redis-Project
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  #打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    log-prefix: mybatis-
#关闭swagger2烦人的提示信息
logging:
  level:
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: warn
